"""Init

Revision ID: 581f0946b38b
Revises: 
Create Date: 2022-11-02 12:32:25.202831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581f0946b38b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(length=2000), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
